version: '3'

services:
  mysql:
    build: .docker/db/dev
    ports:
      - "3306:3306"
    networks:
      - schemaspy-network

  schemaspy:
    build: .docker/schemaspy
    volumes:
      - ./.output:/output
    depends_on:
      - mysql
    tty: true
    networks:
      - schemaspy-network
    command: >
      java -jar schemaspy.jar -o /output/
      -t mysql
      -dp /drivers/mysql-connector-java.jar
      -host mysql
      -port 3306
      -db dev
      -u test
      -p test
      -s dev

networks:
  schemaspy-network:
    external: true