// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tsusowake/go.server/domain/outbound/repository (interfaces: OutboundRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go github.com/tsusowake/go.server/domain/outbound/repository OutboundRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "go.uber.org/mock/gomock"
)

// MockOutboundRepository is a mock of OutboundRepository interface.
type MockOutboundRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboundRepositoryMockRecorder is the mock recorder for MockOutboundRepository.
type MockOutboundRepositoryMockRecorder struct {
	mock *MockOutboundRepository
}

// NewMockOutboundRepository creates a new mock instance.
func NewMockOutboundRepository(ctrl *gomock.Controller) *MockOutboundRepository {
	mock := &MockOutboundRepository{ctrl: ctrl}
	mock.recorder = &MockOutboundRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundRepository) EXPECT() *MockOutboundRepositoryMockRecorder {
	return m.recorder
}
