// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tsusowake/go.server/domain/purchase/repository (interfaces: PurchaseRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go github.com/tsusowake/go.server/domain/purchase/repository PurchaseRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseRepository is a mock of PurchaseRepository interface.
type MockPurchaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseRepositoryMockRecorder
	isgomock struct{}
}

// MockPurchaseRepositoryMockRecorder is the mock recorder for MockPurchaseRepository.
type MockPurchaseRepositoryMockRecorder struct {
	mock *MockPurchaseRepository
}

// NewMockPurchaseRepository creates a new mock instance.
func NewMockPurchaseRepository(ctrl *gomock.Controller) *MockPurchaseRepository {
	mock := &MockPurchaseRepository{ctrl: ctrl}
	mock.recorder = &MockPurchaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseRepository) EXPECT() *MockPurchaseRepositoryMockRecorder {
	return m.recorder
}
