// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go github.com/tsusowake/go.server/domain Repository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	repository "github.com/tsusowake/go.server/domain/auth/repository"
	repository0 "github.com/tsusowake/go.server/domain/inbound/repository"
	repository1 "github.com/tsusowake/go.server/domain/inventory/repository"
	repository2 "github.com/tsusowake/go.server/domain/order/repository"
	repository3 "github.com/tsusowake/go.server/domain/outbound/repository"
	repository4 "github.com/tsusowake/go.server/domain/purchase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockRepository) Auth() repository.AuthRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(repository.AuthRepository)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockRepositoryMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockRepository)(nil).Auth))
}

// Inbound mocks base method.
func (m *MockRepository) Inbound() repository0.InboundRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inbound")
	ret0, _ := ret[0].(repository0.InboundRepository)
	return ret0
}

// Inbound indicates an expected call of Inbound.
func (mr *MockRepositoryMockRecorder) Inbound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inbound", reflect.TypeOf((*MockRepository)(nil).Inbound))
}

// Inventory mocks base method.
func (m *MockRepository) Inventory() repository1.InventoryRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inventory")
	ret0, _ := ret[0].(repository1.InventoryRepository)
	return ret0
}

// Inventory indicates an expected call of Inventory.
func (mr *MockRepositoryMockRecorder) Inventory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inventory", reflect.TypeOf((*MockRepository)(nil).Inventory))
}

// Order mocks base method.
func (m *MockRepository) Order() repository2.OrderRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Order")
	ret0, _ := ret[0].(repository2.OrderRepository)
	return ret0
}

// Order indicates an expected call of Order.
func (mr *MockRepositoryMockRecorder) Order() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockRepository)(nil).Order))
}

// Outbound mocks base method.
func (m *MockRepository) Outbound() repository3.OutboundRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Outbound")
	ret0, _ := ret[0].(repository3.OutboundRepository)
	return ret0
}

// Outbound indicates an expected call of Outbound.
func (mr *MockRepositoryMockRecorder) Outbound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Outbound", reflect.TypeOf((*MockRepository)(nil).Outbound))
}

// Purchase mocks base method.
func (m *MockRepository) Purchase() repository4.PurchaseRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purchase")
	ret0, _ := ret[0].(repository4.PurchaseRepository)
	return ret0
}

// Purchase indicates an expected call of Purchase.
func (mr *MockRepositoryMockRecorder) Purchase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purchase", reflect.TypeOf((*MockRepository)(nil).Purchase))
}
