// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tsusowake/go.server/domain/inbound/repository (interfaces: InboundRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go github.com/tsusowake/go.server/domain/inbound/repository InboundRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "go.uber.org/mock/gomock"
)

// MockInboundRepository is a mock of InboundRepository interface.
type MockInboundRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInboundRepositoryMockRecorder
	isgomock struct{}
}

// MockInboundRepositoryMockRecorder is the mock recorder for MockInboundRepository.
type MockInboundRepositoryMockRecorder struct {
	mock *MockInboundRepository
}

// NewMockInboundRepository creates a new mock instance.
func NewMockInboundRepository(ctrl *gomock.Controller) *MockInboundRepository {
	mock := &MockInboundRepository{ctrl: ctrl}
	mock.recorder = &MockInboundRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboundRepository) EXPECT() *MockInboundRepositoryMockRecorder {
	return m.recorder
}
