/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go.server API
 * API definition for go.server (spec-first).
 * OpenAPI spec version: 0.1.0
 */
import type { Error } from './error';

/**
 * Not Found
 */
export type NotFoundResponse = Error;
